receivers:
  otlp:
    protocols:
      grpc:
      http:
  zipkin:
    endpoint: "0.0.0.0:9411"

extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collector’s performance data
  pprof:
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:

exporters:
  debug:
    verbosity: detailed
  logging:
    loglevel: debug
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

processors:
  batch:
    send_batch_size: 1

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug, prometheus]
      #exporters: [debug]
    traces:
      receivers: [otlp, zipkin]
      processors: []
#      exporters: [jaeger,zipkin,otlp]
      exporters: [debug, otlp/tempo]
      #exporters: [debug]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug, loki]
      #exporters: [debug]