global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'tempo'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
      - targets: ['host.docker.internal:8082']
      - targets: ['host.docker.internal:8081']